/**
 * Regenerates `resolver-data/item_names.txt` from a client's item table.
 *
 *   npx tsx server/extract-item-names.ts "C:/Gravity/Ragnarok/System"
 *
 * Sprite files are named after items in two different ways and this table
 * answers both. A weapon or a shield carries the item *id* -- 크루세이더_남_1116
 * is item 1116 -- while a headgear carries the item's *resource name*, the
 * Korean word the client looks the sprite up by. So each row keeps the id, the
 * resource name and the English display name, and `translate.ts` indexes it by
 * whichever of the first two a file name gives it.
 *
 * The English names come from the client's own `english/iteminfo_new.lub`, so
 * they are the names a player sees in that client rather than a translation of
 * ours. Items with no English name in that file are skipped; the fallback for
 * those is romanisation, not a guess.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readTables, type LuaTable } from "./lua.ts";

const DATA = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "resolver-data");
const OUT = path.join(DATA, "item_names.txt");

const root = process.argv[2];
if (!root) {
  console.error('usage: tsx server/extract-item-names.ts <path to the client\'s System folder>');
  process.exit(1);
}

/** The English table if the client ships one, else the default (Korean) one. */
function itemInfo(): string {
  const candidates = [
    path.join(root, "english", "iteminfo_new.lub"),
    path.join(root, "iteminfo_new.lub"),
    path.join(root, "itemInfo.lub"),
  ];
  for (const file of candidates) if (fs.existsSync(file)) return file;
  throw new Error(`no iteminfo_new.lub under ${root}`);
}

const file = itemInfo();
const table = readTables(file).get("tbl");
if (!table) throw new Error(`${file}: expected a table named tbl`);

const rows: string[] = [];
let unnamed = 0;
for (const [id, value] of table) {
  const item = value as LuaTable | null;
  if (!item) continue;
  const display = String(item.get("identifiedDisplayName") ?? "").trim();
  const resource = String(item.get("identifiedResourceName") ?? "")
    .trim()
    .normalize("NFC");
  if (!/^\d+$/.test(id)) continue;
  // A row whose English name is missing, or is still Korean, keeps its
  // resource name: that is the word the sprite is named after, and it is worth
  // more romanised than the bare item id is.
  const english = display && !/[가-힣]/.test(display) ? display.replace(/\s+/g, " ") : "";
  if (!english) unnamed++;
  if (!english && !resource) continue;
  rows.push(`${id}\t${resource}\t${english}`);
}

rows.sort((a, b) => Number(a.split("\t")[0]) - Number(b.split("\t")[0]));

const header = `# Item id, sprite resource name, English display name.
#
# Generated by \`npx tsx server/extract-item-names.ts <client System folder>\`
# from ${path.basename(path.dirname(file))}/${path.basename(file)}, which is the
# client's own English item table -- these are the names that client shows, not
# a translation of ours. A row with an empty third column has no English name in
# that client; \`translate.ts\` falls back to its resource name, romanised.
#
# Sprite files name items two ways: weapons and shields by id
# (크루세이더_남_1116), headgears by resource name (까마귀모자_남).
`;

fs.writeFileSync(OUT, `${header}${rows.join("\n")}\n`, "utf8");
console.log(
  `${rows.length} items -> ${path.relative(process.cwd(), OUT)} (${unnamed} without an English name)`
);
